/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autopolipo1;


/**
 *
 * @author M2K
 */
public class desktopMenu extends javax.swing.JFrame {

    /**
     * Creates new form desktopMenu
     */
    public desktopMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopMenu = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmEntradas = new javax.swing.JMenu();
        jmViaturas = new javax.swing.JMenuItem();
        jmOficina = new javax.swing.JMenuItem();
        jmCliente = new javax.swing.JMenu();
        jmNovoCliente = new javax.swing.JMenuItem();
        jmProcurarCliente = new javax.swing.JMenuItem();
        jmEditarCliente = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oficina Auto Polipo v1.0");

        javax.swing.GroupLayout desktopMenuLayout = new javax.swing.GroupLayout(desktopMenu);
        desktopMenu.setLayout(desktopMenuLayout);
        desktopMenuLayout.setHorizontalGroup(
            desktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        desktopMenuLayout.setVerticalGroup(
            desktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jMenu1.setText("Ficheiro");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jmEntradas.setText("Viaturas");
        jmEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEntradasActionPerformed(evt);
            }
        });

        jmViaturas.setText("Entrada");
        jmViaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmViaturasActionPerformed(evt);
            }
        });
        jmEntradas.add(jmViaturas);

        jmOficina.setText("Oficina");
        jmOficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmOficinaActionPerformed(evt);
            }
        });
        jmEntradas.add(jmOficina);

        jMenuBar1.add(jmEntradas);

        jmCliente.setText("Clientes");

        jmNovoCliente.setText("Novo Cliente");
        jmNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNovoClienteActionPerformed(evt);
            }
        });
        jmCliente.add(jmNovoCliente);

        jmProcurarCliente.setText("Procurar Cliente");
        jmCliente.add(jmProcurarCliente);

        jmEditarCliente.setText("Editar dados do cliente");
        jmCliente.add(jmEditarCliente);

        jMenuItem6.setText("Listar clientes");
        jmCliente.add(jMenuItem6);

        jMenuBar1.add(jmCliente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopMenu)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEntradasActionPerformed
       
    }//GEN-LAST:event_jmEntradasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmViaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmViaturasActionPerformed
 jifViaturas ifV = new jifViaturas();
        desktopMenu.add(ifV);
        ifV.show();
        ifV.setTitle("Entrada de viaturas");
    }//GEN-LAST:event_jmViaturasActionPerformed

    private void jmNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNovoClienteActionPerformed
         jifClientes jifCliente = new jifClientes();
        jifCliente.setVisible(true);
        desktopMenu.add(jifCliente);
        jifCliente.setTitle("Novo Cliente");
    }//GEN-LAST:event_jmNovoClienteActionPerformed

    private void jmOficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmOficinaActionPerformed
jifConfirmarReparacao jifConfirmarReparacao = new jifConfirmarReparacao();
        jifConfirmarReparacao.setVisible(true);
        desktopMenu.add(jifConfirmarReparacao);
        jifConfirmarReparacao.setTitle("Novo Cliente");        // TODO add your handling code here:
    }//GEN-LAST:event_jmOficinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(desktopMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(desktopMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(desktopMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(desktopMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new desktopMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopMenu;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmCliente;
    private javax.swing.JMenuItem jmEditarCliente;
    private javax.swing.JMenu jmEntradas;
    private javax.swing.JMenuItem jmNovoCliente;
    private javax.swing.JMenuItem jmOficina;
    private javax.swing.JMenuItem jmProcurarCliente;
    private javax.swing.JMenuItem jmViaturas;
    // End of variables declaration//GEN-END:variables
}
